# Generated by Django 4.1 on 2022-08-22 14:14

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="car", options={},),
        migrations.AddField(
            model_name="car",
            name="transmition",
            field=models.CharField(
                blank=True,
                choices=[(1, "Automatic"), (2, "Manual")],
                default=1,
                max_length=17,
                null=True,
            ),
        ),
    ]
