# Generated by Django 4.1 on 2022-08-22 14:37

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_alter_car_options_car_color_car_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=0,
                default_currency="USD",
                max_digits=6,
                null=True,
            ),
        ),
    ]
