# Generated by Django 4.1 on 2022-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0004_car_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car", old_name="fuel_type", new_name="fuel",
        ),
        migrations.AlterField(
            model_name="car",
            name="transmition",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Automatic"), (2, "Manual")],
                default=1,
                null=True,
            ),
        ),
    ]
