# Generated by Django 4.1 on 2022-08-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0005_rename_fuel_type_car_fuel_alter_car_transmition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(upload_to="car/static/images/"),
        ),
    ]
